import './Home.scss'

export default function Home() {
  return (
    <div className='home'>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
      <div>HOME</div>
    </div>
  )
}
